//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAX00000
    {
        public int RECORDID { get; set; }
        public string CATEGORIAID { get; set; }
        public string NOMBRE1 { get; set; }
        public string NOMBRE2 { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string FULLNAME { get; set; }
        public string APODO { get; set; }
        public System.DateTime FNACE { get; set; }
        public string PAISID { get; set; }
        public string CIUDADID { get; set; }
        public string SEXOID { get; set; }
        public bool ESASEGURADO { get; set; }
        public string ARSID { get; set; }
        public string NSSID { get; set; }
        public int COINDICION { get; set; }
        public int RESIDECON { get; set; }
        public string RESIDECON1 { get; set; }
        public int CUIDADOPOR { get; set; }
        public string CUIDADOPOR1 { get; set; }
        public string AGENTSOCIALID { get; set; }
        public string MEDICOID { get; set; }
        public string TERAPISTAID { get; set; }
        public int ROWIDX { get; set; }
        public string ROWGUID { get; set; }
        public System.DateTime ROWCDTE { get; set; }
        public System.DateTime ROWMDTE { get; set; }
        public string ROWUSERID { get; set; }
        public string ROWSGXID { get; set; }
        public string PREDIAGNOSTICO { get; set; }
        public string OTROSPREDIAGNOSTICO { get; set; }
        public string ESTATUS { get; set; }
        public string MOTIVOESTATUS { get; set; }
        public Nullable<decimal> InstitucionesRelacionadas { get; set; }
        public string Diagnostico1 { get; set; }
        public string Diagnostico2 { get; set; }
        public string EstatusPediatria { get; set; }
        public Nullable<decimal> EstatusEVD { get; set; }
        public string EstatusPruebasPendientes { get; set; }
        public string DetalledePruebas { get; set; }
        public string Notas { get; set; }
    }
}
