//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAX00001
    {
        public string REFGUID { get; set; }
        public string FILIACIONID { get; set; }
        public string NSSID { get; set; }
        public string CEDULAID { get; set; }
        public string PASAPORTEID { get; set; }
        public string NOMBRE1 { get; set; }
        public string NOMBRE2 { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string FULLNAME { get; set; }
        public System.DateTime FNACE { get; set; }
        public string ESTCIVILID { get; set; }
        public string ESCOLARIDADID { get; set; }
        public string ESCALAID { get; set; }
        public bool ESEMPLEADO { get; set; }
        public int ROWIDX { get; set; }
        public string ROWGUID { get; set; }
        public System.DateTime ROWCDTE { get; set; }
        public System.DateTime ROWMDTE { get; set; }
        public string ROWUSERID { get; set; }
        public string ROWSGXID { get; set; }
    }
}
