//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAXESCOLARIDAD
    {
        public decimal RECORDID { get; set; }
        public string CENTROEDUCATIVO { get; set; }
        public string GRADO { get; set; }
        public string CATEGORIA { get; set; }
        public string TIPOCATEGORIA { get; set; }
        public string ESTATUS { get; set; }
        public string Director { get; set; }
        public string Maestro { get; set; }
        public string MaestroAsistente { get; set; }
        public System.DateTime FECHADIGITACION { get; set; }
        public string USUARIO { get; set; }
        public string ROWSGXID { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string DISTRITOESCOLAR { get; set; }
        public string RESPONSABLEDISTRITO { get; set; }
        public string ROWGUID { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
    }
}
