//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMX00100
    {
        public string REFGUID { get; set; }
        public string DIRECCION { get; set; }
        public string PAISID { get; set; }
        public string PROVINCIAID { get; set; }
        public string MUNICIPIOID { get; set; }
        public string SECTORID { get; set; }
        public string ZONAID { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public string TEL4 { get; set; }
        public int ROWIDX { get; set; }
        public string ROWGUID { get; set; }
        public System.DateTime ROWCDTE { get; set; }
        public System.DateTime ROWMDTE { get; set; }
        public string ROWUSERID { get; set; }
        public string ROWSGXID { get; set; }
        public string PROPIETARIOTEL1 { get; set; }
        public string PROPIETARIOTEL2 { get; set; }
        public string PROPIETARIOTEL3 { get; set; }
        public string PROPIETARIOTEL4 { get; set; }
    }
}
