//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMX00500
    {
        public string REFGUID { get; set; }
        public string MEDID { get; set; }
        public string TERID { get; set; }
        public string ENFID { get; set; }
        public string ORIGENID { get; set; }
        public System.DateTime FECHAINI { get; set; }
        public System.DateTime FECHAFIN { get; set; }
        public System.DateTime HORAINI { get; set; }
        public System.DateTime HORAFIN { get; set; }
        public string DIA { get; set; }
        public string OBSERVACION { get; set; }
        public bool ASISTIOULTCITA { get; set; }
        public int CITAESTATUS { get; set; }
        public int HORAORDINAL { get; set; }
        public int ROWIDX { get; set; }
        public string ROWGUID { get; set; }
        public System.DateTime ROWCDTE { get; set; }
        public System.DateTime ROWMDTE { get; set; }
        public string ROWUSERID { get; set; }
        public string ROWSGXID { get; set; }
        public Nullable<System.DateTime> TERAPIAINI { get; set; }
        public Nullable<System.DateTime> TERAPIAFIN { get; set; }
        public string DETALLES { get; set; }
        public string TIPO { get; set; }
        public string TIPOGUID { get; set; }
        public string DETTERAPEUTA { get; set; }
        public string DETAUSENCIATERAPEUTA { get; set; }
        public string COMENTARIOCAMBIOESTATUS { get; set; }
        public string ESNUEVO { get; set; }
    }
}
