//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCLASIFICADORES
    {
        public string atipoclas { get; set; }
        public string bidclasif { get; set; }
        public string ctituloclas { get; set; }
        public string dtipoclaspadre { get; set; }
        public string eidclaspadre { get; set; }
        public string etituloclaspad { get; set; }
        public Nullable<System.DateTime> hfechareg { get; set; }
        public System.Guid ROWGUID { get; set; }
    }
}
