//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRDdigitalCAID
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPacienteRdDigital
    {
        public int RECORDID { get; set; }
        public string CENTRO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public Nullable<int> EDAD { get; set; }
        public System.DateTime FECHAINGRESO { get; set; }
        public string TIPOPROCESO { get; set; }
        public string AGENTESOCIAL { get; set; }
        public string EMAILAGENTESOCIAL { get; set; }
        public string CEDULAAGENTESOCIAL { get; set; }
        public string SERVICIORECIBE { get; set; }
        public string HORARIOSERVICIO { get; set; }
        public string NUCLEOFAMILIARNOMBRES { get; set; }
        public string NUCLEOFAMILIARAPELLIDOS { get; set; }
        public string NUCLEOFAMILIARCEDULA { get; set; }
        public string NUCLEOFAMILIARPARENTESCO { get; set; }
        public string ROWSGXID { get; set; }
        public string ROWGUID { get; set; }
        public string PREDIAGNOSTICO { get; set; }
        public string FECHANACIMIENTO { get; set; }
    }
}
